export const LANGUAGES = [
  {
    name: 'Arabic',
    native: 'العربية',
    code: 'ar',
    locale: 'ar-SA',
    flag: '🇸🇦',
    voices: {
      male: [{ id: 'IES4nrmZdUBHByLBde0P', name: 'Haytham' }],
      female: [{ id: 'u0TsaWvt0v8migutHM3M', name: 'GHIZLANE' }],
    },
  },
  {
    name: 'Bulgarian',
    native: 'български',
    code: 'bg',
    locale: 'bg-BG',
    flag: '🇧🇬',
    voices: {
      male: [{ id: 'j9jfwdrw7BRfcR43Qohk', name: 'Frederick Surrey' }],
      female: [{ id: 'M1ydWt7KnBCiuv4CnEDC', name: 'Milena' }],
    },
  },
  {
    name: 'Chinese',
    native: '中文',
    code: 'zh',
    locale: 'zh-CN',
    flag: '🇨🇳',
    voices: {
      male: [{ id: '4VZIsMPtgggwNg7OXbPY', name: 'James Gao' }],
      female: [{ id: 'bhJUNIXWQQ94l8eI2VUf', name: 'Amy' }],
    },
  },
  {
    name: 'Croatian',
    native: 'hrvatski',
    code: 'hr',
    locale: 'hr-HR',
    flag: '🇭🇷',
    voices: {
      male: [{ id: 'j9jfwdrw7BRfcR43Qohk', name: 'Frederick Surrey' }],
      female: [{ id: 'tnSpp4vdxKPjI9w0GnoV', name: 'Hope' }],
    },
  },
  {
    name: 'Czech',
    native: 'čeština',
    code: 'cs',
    locale: 'cs-CZ',
    flag: '🇨🇿',
    voices: {
      male: [{ id: 'uYFJyGaibp4N2VwYQshk', name: 'Adam' }],
      female: [{ id: 'tnSpp4vdxKPjI9w0GnoV', name: 'Hope' }],
    },
  },
  {
    name: 'Danish',
    native: 'dansk',
    code: 'da',
    locale: 'da-DK',
    flag: '🇩🇰',
    voices: {
      male: [{ id: 'j9jfwdrw7BRfcR43Qohk', name: 'Frederick Surrey' }],
      female: [{ id: 'gD1IexrzCvsXPHUuT0s3', name: 'Sara Martin' }],
    },
  },
  {
    name: 'Dutch',
    native: 'Nederlands',
    code: 'nl',
    locale: 'nl-NL',
    flag: '🇳🇱',
    voices: {
      male: [{ id: 'wqDY19Brqhu7UCoLadPh', name: 'Jann' }],
      female: [{ id: 'SXBL9NbvTrjsJQYay2kT', name: 'Melanie' }],
    },
  },
  {
    name: 'English',
    native: 'English',
    code: 'en',
    locale: 'en-US',
    flag: '🇺🇸',
    voices: {
      male: [{ id: 'NYC9WEgkq1u4jiqBseQ9', name: 'Russell' }],
      female: [{ id: 'tnSpp4vdxKPjI9w0GnoV', name: 'Hope' }],
    },
  },
  {
    name: 'Filipino',
    native: 'Filipino',
    code: 'tl',
    locale: 'tl-PH',
    flag: '🇵🇭',
    voices: {
      male: [{ id: 'rVz5W5gAIQHsFZox2HtT', name: 'Kuya' }],
      female: [{ id: 'RnW8EXHv9GqGMgyP0sXG', name: 'Ate Lyn' }],
    },
  },
  {
    name: 'Finnish',
    native: 'suomi',
    code: 'fi',
    locale: 'fi-FI',
    flag: '🇫🇮',
    voices: {
      male: [{ id: '8Es4wFxsDlHBmFWAOWRS', name: 'William Shanks' }],
      female: [{ id: '7eVMgwCnXydb3CikjV7a', name: 'Lea' }],
    },
  },
  {
    name: 'French',
    native: 'français',
    code: 'fr',
    locale: 'fr-FR',
    flag: '🇫🇷',
    voices: {
      male: [{ id: 'ohItIVrXTBI80RrUECOD', name: 'Guillaume' }],
      female: [{ id: 'McVZB9hVxVSk3Equu8EH', name: 'Audrey' }],
    },
  },
  {
    name: 'German',
    native: 'Deutsch',
    code: 'de',
    locale: 'de-DE',
    flag: '🇩🇪',
    voices: {
      male: [{ id: 'LMwgkTZL66bLQfT9Y7py', name: 'Henry' }],
      female: [{ id: 'Dr5ws89ILcknhL7xh4JG', name: 'Johanna' }],
    },
  },
  {
    name: 'Greek',
    native: 'ελληνικά',
    code: 'el',
    locale: 'el-GR',
    flag: '🇬🇷',
    voices: {
      male: [{ id: 'n0vzWypeCK1NlWPVwhOc', name: 'Theos' }],
      female: [{ id: '0oYUKTNPbymIKVAkDQqh', name: 'Sofia' }],
    },
  },
  {
    name: 'Hindi',
    native: 'हिन्दी',
    code: 'hi',
    locale: 'hi-IN',
    flag: '🇮🇳',
    voices: {
      male: [{ id: 'zgqefOY5FPQ3bB7OZTVR', name: 'Niraj' }],
      female: [{ id: 'gHu9GtaHOXcSqFTK06ux', name: 'Anjali' }],
    },
  },
  {
    name: 'Hungarian',
    native: 'magyar',
    code: 'hu',
    locale: 'hu-HU',
    flag: '🇭🇺',
    voices: {
      male: [{ id: 'M336tBVZHWWiWb4R54ui', name: 'David' }],
      female: [{ id: 'xjlfQQ3ynqiEyRpArrT8', name: 'Vera' }],
    },
  },
  {
    name: 'Indonesian',
    native: 'Bahasa Indonesia',
    code: 'id',
    locale: 'id-ID',
    flag: '🇮🇩',
    voices: {
      male: [{ id: 'RWiGLY9uXI70QL540WNd', name: 'Putra' }],
      female: [{ id: 'iWydkXKoiVtvdn4vLKp9', name: 'Cahaya' }],
    },
  },
  {
    name: 'Italian',
    native: 'italiano',
    code: 'it',
    locale: 'it-IT',
    flag: '🇮🇹',
    voices: {
      male: [{ id: '', name: 'Giovanni Rossi' }],
      female: [{ id: 'fQmr8dTaOQq116mo2X7F', name: 'Samanta' }],
    },
  },
  {
    name: 'Japanese',
    native: '日本語',
    code: 'ja',
    locale: 'ja-JP',
    flag: '🇯🇵',
    voices: {
      male: [{ id: 'b34JylakFZPlGS0BnwyY', name: 'Kenzo' }],
      female: [{ id: '8EkOjt4xTPGMclNlh1pk', name: 'Morioki' }],
    },
  },
  {
    name: 'Korean',
    native: '한국어',
    code: 'ko',
    locale: 'ko-KR',
    flag: '🇰🇷',
    voices: {
      male: [{ id: '1W00IGEmNmwmsDeYy7ag', name: 'KKC' }],
      female: [{ id: 'AW5wrnG1jVizOYY7R1Oo', name: 'JiYoung' }],
    },
  },
  {
    name: 'Malay',
    native: 'Bahasa Melayu',
    code: 'ms',
    locale: 'ms-MY',
    flag: '🇲🇾',
    voices: {
      male: [{ id: 'C1gMsiiE7sXAt59fmvYg', name: 'Hasnan' }],
      female: [{ id: 'Athira', name: 'BeIxObt4dYBRJLYoe1hU' }],
    },
  },
  {
    name: 'Norwegian',
    native: 'norsk',
    code: 'no',
    locale: 'nb-NO',
    flag: '🇳🇴',
    voices: {
      male: [{ id: 'dgrgQcxISbZtq517iweJ', name: 'Ola' }],
      female: [{ id: 'b3jcIbyC3BSnaRu8avEk', name: 'Emma' }],
    },
  },
  {
    name: 'Polish',
    native: 'polski',
    code: 'pl',
    locale: 'pl-PL',
    flag: '🇵🇱',
    voices: {
      male: [{ id: 'W3ryZpL8gFeUBUllKisa', name: 'Maciej' }],
      female: [{ id: 'W0sqKm1Sfw1EzlCH14FQ', name: 'Beata' }],
    },
  },
  {
    name: 'Portuguese',
    native: 'português',
    code: 'pt',
    locale: 'pt-PT',
    flag: '🇵🇹',
    voices: {
      male: [{ id: 'NGS0ZsC7j4t4dCWbPdgO', name: 'Dhyogo Azevedo' }],
      female: [{ id: '33B4UnXyTNbgLmdEDh5P', name: 'Keren' }],
    },
  },
  {
    name: 'Romanian',
    native: 'română',
    code: 'ro',
    locale: 'ro-RO',
    flag: '🇷🇴',
    voices: {
      male: [{ id: 'h3aQ5g69oxB0wpernpfx', name: 'Ciprian Pop' }],
      female: [{ id: '3z9q8Y7plHbvhDZehEII', name: 'Antonia' }],
    },
  },
  {
    name: 'Russian',
    native: 'русский',
    code: 'ru',
    locale: 'ru-RU',
    flag: '🇷🇺',
    voices: {
      male: [{ id: 'gJEfHTTiifXEDmO687lC', name: 'Prince Nuri' }],
      female: [{ id: 'OowtKaZH9N7iuGbsd00l', name: 'Veronica С.' }],
    },
  },
  {
    name: 'Slovak',
    native: 'slovenčina',
    code: 'sk',
    locale: 'sk-SK',
    flag: '🇸🇰',
    voices: {
      male: [{ id: 'd6IbhdqAKkXCCVuJjbie', name: 'Peter' }],
      female: [{ id: 'qBDvhofpxp92JgXJxDjB', name: 'Lily Wolff' }],
    },
  },
  {
    name: 'Spanish',
    native: 'español',
    code: 'es',
    locale: 'es-ES',
    flag: '🇪🇸',
    voices: {
      male: [{ id: '9F4C8ztpNUmXkdDDbz3J', name: 'Dan Dan' }],
      female: [{ id: 'qHkrJuifPpn95wK3rm2A', name: 'Andrea' }],
    },
  },
  {
    name: 'Swedish',
    native: 'svenska',
    code: 'sv',
    locale: 'sv-SE',
    flag: '🇸🇪',
    voices: {
      male: [{ id: 'x0u3EW21dbrORJzOq1m9', name: 'Adam' }],
      female: [{ id: '4Ct5uMEndw4cJ7q0Jx0l', name: 'Elin' }],
    },
  },
  {
    name: 'Turkish',
    native: 'Türkçe',
    code: 'tr',
    locale: 'tr-TR',
    flag: '🇹🇷',
    voices: {
      male: [{ id: 'GLHtjkeLJ9Rxcv9JhLmh', name: 'MUHAMMER ARABACI' }],
      female: [{ id: 'NNn9dv8zq2kUo7d3JSGG', name: 'Derya' }],
    },
  },
  {
    name: 'Ukrainian',
    native: 'українська',
    code: 'uk',
    locale: 'uk-UA',
    flag: '🇺🇦',
    voices: {
      male: [{ id: '9Sj8ugvpK1DmcAXyvi3a', name: 'Alex Nekrasov' }],
      female: [{ id: '0ZQZuw8Sn4cU0rN1Tm2K', name: 'Yaroslava' }],
    },
  },
  {
    name: 'Vietnamese',
    native: 'Tiếng Việt',
    code: 'vi',
    locale: 'vi-VN',
    flag: '🇻🇳',
    voices: {
      male: [{ id: '3VnrjnYrskPMDsapTr8X', name: 'DangTungDuy' }],
      female: [{ id: 'BlZK9tHPU6XXjwOSIiYA', name: 'HuyenTrang' }],
    },
  },
] as const;
